Repository tungjty/hello-spring-boot, pull requests merged in 2021-10, with the labels that each got.

#4 Release4.0.4 jonny dang
  src/main/java/com/example/hellospringboot/Java_404_jonny_dang.java
Labels: help wanted

#8 Jonny/documents
  src/main/java/com/example/hellospringboot/Java_404_jonny_dang.java
Labels: enhancement

#9 Alien Ngan post first Java406_alien_ngan.java
  src/main/java/com/example/hellospringboot/Java406_alien_ngan.java
Labels: duplicate
